/** Esempi nei campi di testo liberi — prefisso "es." */
export const PLACEHOLDER = {
  notePreventivo: "es. Descrivi qui le tue note aggiuntive",
  noteCliente: "es. Preferisce essere contattato il pomeriggio",
  notePagamento: "es. Pagamento entro 30 giorni dalla fattura",
  kmRimborso: "es. 120",
  spesaVivaNome: "es. Treno Milano-Roma",
  importoEuro: "es. 45,00",
  nomeCliente: "es. Mario Rossi",
  telefono: "es. 339 1234567",
  email: "es. mario@example.com",
  indirizzo: "es. Via Roma 1, Milano",
  nomeServizio: "es. Riprese video mezza giornata",
  descrizioneServizio: "es. Operatore con camera 4K, audio ambiente incluso",
  costoServizio: "es. 400,00",
  quantita: "es. 1",
  chatPreventivo: "es. Preventivo ristrutturazione bagno 6 mq",
  nomeAzienda: "es. Studio Rossi SRL",
  categoria: "es. Videomaker",
  citta: "es. Roma",
  piva: "es. 12345678901",
  tono: "es. Professionale e diretto",
  firma: "es. Mario Rossi",
  coloreBrand: "es. 0D1B2A",
  loginEmail: "es. mario@example.com",
} as const;
